name: Commit Checks
on: 
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  merge_group:
    types: [checks_requested]
jobs:
  Pull-Request-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run test-cov --if-present
      - run: npm run lint
      - run: npm run pretty-check --if-present
